project:
  type: website
  output-dir: docs

website:
  title: "Methods of Data Collection by Libby Smith"
  margin-footer: |
   ![ ](/utdfooter.jpg)

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: CV
      - text: Assignments
      - href: writing.qmd
        text: Analysis Writing
        menu: 
          - href: assignment1.qmd
            text: Create a Qualtrics Survey
          - href: assignment2.qmd
            text: Google Trends VS Rstudio gtrends
format:
  html:
    theme: spacelab
    light: flatly
    dark: darkly
    css: styles.css
    toc: true

editor: visual

